[package]
name = "codotaku_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
bytemuck = { version = "1.19.0", features = ["derive"] }
nalgebra = "0.33.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
winit = "0.30.5"
anyhow = "1.0.91"
